<?php

function tinypass_admin_settings() {

	if (isset($_POST['_Submit'])) {
		update_option('tinypass_settings', $_POST['tinypass']);
	}

	$options = get_option('tinypass_settings');
	?>
	<div id="poststuff" class="metabox-holder has-right-sidebar">
		<?php if (!empty($_POST['_Submit'])) : ?>
			<div id="message" class="updated fade"><p><strong><?php _e('Options saved.') ?></strong></p></div>
		<?php endif; ?>

		<div class="wrap">
			<h2><?php _e('TinyPass Settings'); ?></h2>
			<form action="" method="post" id="tinypass-conf" style="margin-left:30px; ">


				<div class="postbox">
					<h3><?php _e('TinyPass Enabled') ?> </h3>
					<div class="inside">
						<table class="form-table">

							<tr>
								<td>
									<?php _e('TinyPass Enabled'); ?>
								</td>
								<td>
									<?php if ($options['enabled'] == 'on' || $options['enabled']): ?>
										<input type="checkbox" name="tinypass[enabled]" checked=true>
									<?php else: ?>
										<input type="checkbox" name="tinypass[enabled]">
									<?php endif; ?>
								</td>
							</tr>

							<tr>
								<th scope="row"><?php _e('TinyPass Environment'); ?></th>
								<td>
									<?php if ($options['env'] == 0): ?>
										<input type="radio" name="tinypass[env]" value="0" checked=true><label><?php _e('Sandbox - for testing only'); ?></label><br>
										<input type="radio" name="tinypass[env]" value="1"><label><?php _e('Live - for live payments'); ?></label>
									<?php else: ?>
										<input type="radio" name="tinypass[env]" value="0"><label><?php _e('Sandbox - for testing only'); ?></label><br>
										<input type="radio" name="tinypass[env]" value="1"checked=true><label><?php _e('Live - for live payments'); ?></label>
									<?php endif; ?>
								</td>
							</tr>
						</table>
					</div>
				</div>

				<div class="postbox">
					<h3><?php _e('Application IDs and Keys'); ?> </h3>
					<div class="inside">

						<table class="form-table">

							<tr valign="top">
								<th scope="row"><?php _e('Application ID (Sandbox)'); ?></th>
								<td>
									<input id="aid_sand" name="tinypass[aid_sand]" type="text" size="10" maxlength="10" value="<?php echo $options['aid_sand']; ?>"/><br>
									<span class="description">The Application ID (sandbox) is auto-generated by TinyPass and can be retrieved from your account at <a href="http://sandbox.tinypass.com/member/merch">http://sandbox.tinypass.com</a></span>
								</td>
							</tr>

							<tr valign="top">
								<th scope="row"><?php _e('Application Secret Key (Sandbox)'); ?></th>
								<td>
									<input id="secret_key_sand" name="tinypass[secret_key_sand]" type="text" size="40" maxlength="40" value="<?php echo $options['secret_key_sand']; ?>" style="" /><br>
									<span class="description">The Secret Key (sandbox) is auto-generated by TinyPass and can be retrieved from your account at <a href="http://sandbox.tinypass.com/member/merch">http://sandbox.tinypass.com</a></span><br>
									<br>
									<span class="description"><strong>Note:</strong> The Sandbox environment is for testing the TinyPass experience.  When enabled, no actual payment will be processed.</span>
								</td>
							</tr>
							<tr><td></td></tr>
							<tr><td></td></tr>
							<tr valign="top">
								<th scope="row"><?php _e('Application ID (Live)'); ?></th>
								<td>
									<input id="aid_prod" name="tinypass[aid_prod]" type="text" size="10" maxlength="10" value="<?php echo $options['aid_prod']; ?>"/><br>
									<span class="description">The Application ID (Live) is auto-generated by TinyPass and can be retrieved from your account at <a href="http://sandbox.tinypass.com/member/merch">http://www.tinypass.com</a></span>
								</td>
							</tr>

							<tr valign="top">
								<th scope="row"><?php _e('Application Secret Key (Live)'); ?></th>
								<td>
									<input id="secret_key_prod" name="tinypass[secret_key_prod]" type="text" size="40" maxlength="40" value="<?php echo $options['secret_key_prod']; ?>" style="" /><br>
									<span class="description">The Secret Key (Live) is auto-generated by TinyPass and can be retrieved from your account at <a href="http://sandbox.tinypass.com/member/merch">http://www.tinypass.com</a></span>
								</td>
							</tr>

						</table>
					</div>
				</div>

				<div class="postbox">
					<h3><?php _e('Other'); ?> </h3>
					<div class="inside">

						<table class="form-table">
							<tr valign="top">
								<th scope="row"><?php _e('Denied access message'); ?></th>
								<td>
									<textarea cols="80" rows="12" name="tinypass[access_message]" ><?php echo stripslashes($options['access_message']) ?></textarea>
									<br>
									<div class="description">This message will be displayed when access is denied to a resource</div>
									<div class="description"><strong>Note:</strong>  This support the use of HTML tags</div>

									<br>
									<strong>Custom button postion:</strong><br>
									<span class="description">The TinyPass button can be position by using the token [TP_BUTTON] in the text area about.
										This will allow your site to place to button into a specific position in your HTML</span>
									<strong>Example:</strong><br>
									<pre>
						&lt;table&gt;
							&lt;tr&gt;
								&lt;td&gt; Left Column &lt;/td&gt;
								&lt;td&gt; <b>[TP_BUTTON]</b> &lt;/td&gt;
								&lt;td&gt; Right Column &lt;/td&gt;
							&lt;tr&gt;
						&lt;/table&gt;

									</pre>
									<br>
								</td>
							</tr>

						</table>
					</div>
				</div>

				<p>
					<input type="submit" name="_Submit" id="publish" value="Save Changes" tabindex="4" class="button-primary" />
				</p>

			</form>
		</div>
	</div>

<?php } ?>